# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20171105_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videourl',
            field=models.CharField(default='', max_length=100, verbose_name='视频地址'),
        ),
    ]
