# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(blank=True, choices=[('pxjg', '培训机构'), ('gr', '个人'), ('gx', '高校')], max_length=30, null=True, verbose_name='机构类别'),
        ),
    ]
