# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20171101_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='ogr/teacher/%Y/%m', verbose_name='教师图像'),
        ),
    ]
